{% set name = "seed-isort-config" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: be4cfef8f9a3fe8ea1817069c6b624538ac0b429636ec746edeb27e98ed628c8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - seed-isort-config = seed_isort_config:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aspy.refactor-imports

test:
  imports:
    - seed_isort_config
  commands:
    - seed-isort-config --help

about:
  home: https://github.com/asottile/seed-isort-config
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Statically populate the known_third_party isort setting
  dev_url: https://github.com/asottile/seed-isort-config

extra:
  recipe-maintainers:
    - scopatz
